services:
  backend:
    build: ./backend
    container_name: backend
    command: ["python", "-m", "app.main", "false"]
    volumes:
      - ./backend:/code  # Mount the entire backend folder for the code
      - ./backend/data:/code/data  # Mount only the data folder for SQLite persistence

    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: ["serve", "-s", "build", "-l", "tcp://0.0.0.0:3000"]

volumes:
  sqlite_data:
    driver: local